name: Frontend CI - Build and Test

on:
  push:
    branches:
      - main
      - staging
      - 'feature/**'
  pull_request:
    branches:
      - main
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      # - name: Run build (à activer plus tard)
      #   run: npm run build

      # - name: Run tests (à activer plus tard)
      #   run: npm run test

      # - name: Enforce 80% code coverage (à activer plus tard)
      #   run: |
      #     echo "Vérification couverture > 80% - À activer plus tard"

  # check-version-change:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
  #   outputs:
  #     version_changed: ${{ steps.check.outputs.changed }}
  #
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #
  #     - name: Get current version from package.json
  #       id: current
  #       run: |
  #         current_version=$(jq -r .version package.json)
  #         echo "version=$current_version" >> $GITHUB_OUTPUT
  #
  #     - name: Get version from main branch
  #       id: main
  #       run: |
  #         git fetch origin main
  #         main_version=$(git show origin/main:package.json | jq -r .version)
  #         echo "version=$main_version" >> $GITHUB_OUTPUT
  #
  #     - name: Compare versions
  #       id: check
  #       run: |
  #         if [ "${{ steps.current.outputs.version }}" != "${{ steps.main.outputs.version }}" ]; then
  #           echo "changed=true" >> $GITHUB_OUTPUT
  #         else
  #           echo "changed=false" >> $GITHUB_OUTPUT
  #         fi

  deploy-to-render:
    # needs: [build-and-test, check-version-change]
    # if: needs.check-version-change.outputs.version_changed == 'true' && github.ref == 'refs/heads/main'
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deploy (frontend)
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
